### ISSUE TITLE
Cannot load project, problem

### ISSUE THREAD

**Issue by nikitavoloboev** [expo/react-conf-app#5]
<img width="448" alt="image" src="https://github.com/expo/react-conf-app/assets/6391776/b9aa3477-076b-4082-bc5f-6c9ade32fd05">

Getting this, not sure why.

**Comment by nikitavoloboev** [comment]
getting this now too:

```
npx expo run:ios
Error: xcrun simctl boot 66B36CDE-E8DC-4B59-A732-50BBAD0567C8 exited with non-zero code: 60
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
Unable to boot the Simulator.
launchd failed to respond.
Underlying error (domain=com.apple.SimLaunchHostService.RequestError, code=4):
 Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding
Error: xcrun simctl boot 66B36CDE-E8DC-4B59-A732-50BBAD0567C8 exited with non-zero code: 60
    at ChildProcess.completionListener (/Users/omrshn/src/react-conf-app/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at xcrunAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/xcrun.js:33:48)
    at simctlAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:262:34)
    at bootDeviceAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:195:15)
    at Object.bootAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:175:11)
    at action (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:130:28)
    at waitForActionAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/utils/delay.js:25:26)
    at ensureSimulatorOpenAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:126:62)
    at async AppleDeviceManager.resolveAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:155:24)
    at async resolveDeviceAsync (/Users/omrshn/src/react-conf-app/node_modules/@expo/cli/build/src/run/ios/options/resolveDevice.js:112:95)
    ```

**Comment by nikitavoloboev** [comment]
Okay it's resolved now.
